name: Test
on:
  workflow_dispatch:

jobs:
  test:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4
      - name: run script
        if: always()
        run: bash ./test-signals.sh
